# OpenSSL #####################################################################

[OpenSSL]
version = "1.1.1m"
disabled_targets = ["ios", "windows"]

[OpenSSL.linux]
version = ""
install_from_source = false


# Python ######################################################################

[Python]
version = "3.11.0"
install_host_from_source = true

[Python.win]
install_host_from_source = false


# PyQt ########################################################################

[PyQt]
version = "5.15.9"

[PyQt.android]
disabled_features = ["PyQt_Desktop_OpenGL", "PyQt_Printer"]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtAndroidExtras"]

[PyQt.ios]
disabled_features = ["PyQt_Desktop_OpenGL", "PyQt_MacOSXOnly",
        "PyQt_MacCocoaViewContainer", "PyQt_Printer", "PyQt_Process",
        "PyQt_NotBootstrapped"]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtMacExtras"]

[PyQt.linux]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtX11Extras"]

[PyQt.macos]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtMacExtras"]

[PyQt.win]
disabled_features = ["PyQt_Desktop_OpenGL"]
installed_modules = ["QtCore", "QtGui", "QtNetwork", "QtWidgets",
        "QtWinExtras"]


# PyQt3D ######################################################################

[PyQt3D]
version = "5.15.9"


# PyQtChart ###################################################################

# [PyQtChart]
# version = "5.15.9"


# PyQtDataVisualization #######################################################

[PyQtDataVisualization]
version = "5.15.9"


# PyQtNetworkAuth #############################################################

[PyQtNetworkAuth]
version = "5.15.9"


# PyQtPurchasing ##############################################################

[PyQtPurchasing]
version = "5.15.9"


# QScintilla ##################################################################

[QScintilla]
version = "2.13.3"


# Qt ##########################################################################

[Qt]
version = "5.15.9"
edition = "opensource"
configure_options = ["-opengl", "desktop", "-no-dbus", "-qt-pcre"]
skip = ["qtactiveqt", "qtconnectivity", "qtdoc", "qtgamepad", "qtlocation",
        "qtmultimedia", "qtquickcontrols", "qtquickcontrols2",
        "qtremoteobjects", "qtscript", "qtscxml", "qtsensors", "qtserialbus",
        "qtserialport", "qtspeech", "qtsvg", "qttools", "qttranslations",
        "qtwayland", "qtwebchannel", "qtwebengine", "qtwebsockets",
        "qtwebview", "qtxmlpatterns"]

[Qt.android]
install_from_source = false
ssl = "openssl-linked"

[Qt.ios]
install_from_source = false
ssl = "securetransport"

[Qt.linux]
ssl = "openssl-runtime"

[Qt.macos]
ssl = "openssl-linked"

[Qt.win]
ssl = "openssl-linked"
static_msvc_runtime = true


# SIP #########################################################################

[SIP]
abi_major_version = 12
module_name = "PyQt5.sip"



# zlib ########################################################################

[zlib]
install_from_source = false

[zlib.win]
version = "1.2.13"
install_from_source = true
static_msvc_runtime = true
